codesign (-d) is now optional

diff --git a/notarizer b/notarizer
--- a/notarizer
+++ b/notarizer
@@ -18,7 +18,7 @@
 
 Usage()
 {
-  echo "Usage: notarizer -d <developer identity name> -k <keychain profile name> <app path>"
+  echo "Usage: notarizer [-d <developer identity name>] -k <keychain profile name> <app path>"
 }
 
 Help()
@@ -31,10 +31,10 @@ Help()
   Usage
   echo "options:"
   echo "h     Print this Help."
-  echo "d     Developer Identity name (excluding team ID)."
-  echo "k     Name of Keychain-stored Profile with app store connect credentials"
+  echo "d     Codesign app using provided Developer Identity name, excluding team ID (optional, skips codesign if not specified)"
+  echo "k     Name of Keychain-stored Profile with app store connect credentials (mandatory)"
   echo
-  echo "Requires a valid Developer ID certificate to be installed in the keychain and App Store Connect credentials stored in a keychain profile."
+  echo "Requires a valid Developer ID certificate to be installed in the keychain to codesign the app, and App Store Connect credentials stored in a keychain profile to notarize the app."
   echo
   echo "To discover names and teams IDs of currently installed Developer Identities, just use:"
   echo "security find-identity -p basic -v"
@@ -71,9 +71,6 @@ if [[ $# -eq 0 ]]; then
 fi
 
 # Check if mandatory arguments are present
-if [[ -z $DEVELOPER_IDENTITY ]]; then
-  echo "Missing argument: -d <developer identity>" >&2; exit 1
-fi
 
 if [[ -z $KEYCHAIN_PROFILE ]]; then
   echo "Missing argument: -k <keychain profile>" >&2; exit 1
@@ -92,14 +89,16 @@ TEXTYELLOW="\033[1;33m"
 TEXTNORMAL="\033[0m"
 
 # codesign app
-echo -e $TEXTGREEN"Codesigning $APP_NAME... "$TEXTNORMAL
-codesign --force --options runtime --deep --sign "$DEVELOPER_IDENTITY" "$APP_NAME"
-if [ $? -eq 0 ]
-then
-  echo -e $TEXTGREEN"Codesign successful"$TEXTNORMAL
-else
-  echo -e $TEXTRED"FAILED"$TEXTNORMAL
-  exit 1
+if [[ "$DEVELOPER_IDENTITY" ]]; then
+  echo -e $TEXTGREEN"Codesigning $APP_NAME... "$TEXTNORMAL
+  codesign --force --options runtime --deep --sign "$DEVELOPER_IDENTITY" "$APP_NAME"
+  if [ $? -eq 0 ]
+  then
+    echo -e $TEXTGREEN"Codesign successful"$TEXTNORMAL
+  else
+    echo -e $TEXTRED"FAILED"$TEXTNORMAL
+    exit 1
+  fi
 fi
 
 # zip app
@@ -116,13 +115,6 @@ fi
 # notarize app
 echo -e $TEXTGREEN"Sending package to Apple for notarization... "$TEXTNORMAL
 xcrun notarytool submit "$APP_NAME.zip" --keychain-profile "$KEYCHAIN_PROFILE" --wait
-if [ $? -eq 0 ]
-then
-  echo -e $TEXTGREEN"Success"$TEXTNORMAL
-else
-  echo -e $TEXTRED"FAILED"$TEXTNORMAL
-  exit 1
-fi
 
 # remove zip
 rm "$APP_NAME.zip"
@@ -134,6 +126,6 @@ if [ $? -eq 0 ]
 then
   echo -e $TEXTGREEN"Success"$TEXTNORMAL
 else
-  echo -e $TEXTRED"FAILED"$TEXTNORMAL
+  echo -e $TEXTRED"FAILED, to see log use: xcrun notarytool log <Submission ID> --keychain-profile \"$KEYCHAIN_PROFILE\""$TEXTNORMAL
   exit 1
 fi
